const textureData = {
    concrete2: {
        ext: 'png',
        sizes: [2048, 512],
        map: 'concrete2_albedo',
        bumpMap: 'concrete2_Height',
        metalnessMap: 'concrete2_Metallic',
        normalMap: 'concrete2_Normal-ogl',
        roughnessMap: 'concrete2_Roughness',
        aoMap: 'concrete2-ao',
        files: [
            'concrete2_albedo_512.png',
            'concrete2_albedo.png',
            'concrete2_Height_512.png',
            'concrete2_Height.png',
            'concrete2_Metallic_512.png',
            'concrete2_Metallic.png',
            'concrete2_Normal-ogl_512.png',
            'concrete2_Normal-ogl.png',
            'concrete2_Roughness_512.png',
            'concrete2_Roughness.png',
            'concrete2-ao_512.png',
            'concrete2-ao.png',
        ],
    },
    darktiles1: {
        ext: 'png',
        sizes: [2048],
        map: 'darktiles1_basecolor',
        bumpMap: null,
        metalnessMap: 'darktiles1_metallic',
        normalMap: 'darktiles1_normal-ogl',
        roughnessMap: 'darktiles1_roughness',
        aoMap: 'darktiles1_AO',
        files: [
            'darktiles1_AO.png',
            'darktiles1_basecolor.png',
            'darktiles1_metallic.png',
            'darktiles1_normal-ogl.png',
            'darktiles1_roughness.png',
        ],
    },
    camo: {
        ext: 'jpg',
        sizes: [1024],
        map: 'Fabric_Camo_003_basecolor',
        bumpMap: 'Fabric_Camo_003_height',
        metalnessMap: null,
        normalMap: 'Fabric_Camo_003_normal',
        roughnessMap: 'Fabric_Camo_003_roughness',
        aoMap: 'Fabric_Camo_003_ambientOcclusion',
        files: [
            'Fabric_Camo_003_basecolor.jpg',
            'Fabric_Camo_003_height.jpg',
            'Fabric_Camo_003_normal.jpg',
            'Fabric_Camo_003_roughness.jpg',
            'Fabric_Camo_003_ambientOcclusion.jpg',
        ],
    },
    metalpanel8: {
        ext: 'jpg',
        sizes: [1024],
        map: 'Metal_Panel_008_basecolor',
        bumpMap: 'Metal_Panel_008_height',
        metalnessMap: 'Metal_Panel_008_metallic',
        normalMap: 'Metal_Panel_008_normal',
        roughnessMap: 'Metal_Panel_008_roughness',
        aoMap: 'Metal_Panel_008_ambientOcclusion',
        files: [
            'Metal_Panel_008_basecolor.jpg',
            'Metal_Panel_008_height.jpg',
            'Metal_Panel_008_metallic.jpg',
            'Metal_Panel_008_normal.jpg',
            'Metal_Panel_008_roughness.jpg',
            'Metal_Panel_008_ambientOcclusion.jpg',
        ],
    },
    scifipanels4: {
        ext: 'png',
        sizes: [1024],
        map: 'SciFiPanels04_1K_albedo',
        bumpMap: 'SciFiPanels04_1K_height',
        metalnessMap: 'SciFiPanels04_1K_metallic',
        normalMap: 'SciFiPanels04_1K_normal',
        roughnessMap: 'SciFiPanels04_1K_roughness',
        aoMap: 'SciFiPanels04_1K_ao',
        files: [
            'SciFiPanels04_1K_albedo.png',
            'SciFiPanels04_1K_height.png',
            'SciFiPanels04_1K_metallic.png',
            'SciFiPanels04_1K_normal.png',
            'SciFiPanels04_1K_roughness.png',
            'SciFiPanels04_1K_ao.png',
        ],
    }
};

export default textureData;